import type { RelicDevice } from '../../sdk/types'

/**
 * MOCK — seed device registry for the Relic Device Mesh.
 * On real hardware these records come from mesh discovery (mDNS / BLE / Thread)
 * plus the identity service; nothing here talks to real hardware.
 */
const now = Date.now()

export const THIS_DEVICE_ID = 'relic-laptop'

export const seedDevices: RelicDevice[] = [
  {
    id: 'relic-laptop',
    name: 'Relic Laptop',
    type: 'laptop',
    status: 'online',
    presence: 'local',
    location: 'Studio',
    hardware: 'x86-64 · 16 CORE · 64 GB',
    identity: { fingerprint: 'RLC·7F3A·91C2·E04D', trust: 'verified', enrolled: '2026-03-02' },
    capabilities: ['display', 'large-display', 'audio', 'video', 'keyboard', 'camera', 'microphone', 'compute', 'gpu', 'storage', 'windows-runtime'],
    network: { transport: 'wifi', address: '10.0.7.21', latencyMs: 0, signal: 0.94 },
    lastSeen: now,
    battery: 0.86,
    state: { cpu: 0.18, memory: 0.41, storageUsed: 1.21, storageTotal: 2 },
  },
  {
    id: 'relic-desktop',
    name: 'Relic Desktop',
    type: 'desktop',
    status: 'offline',
    presence: 'sleeping',
    location: 'Office',
    hardware: 'x86-64 · 32 CORE · 128 GB · RTX',
    identity: { fingerprint: 'RLC·22B8·0F6E·A7C1', trust: 'verified', enrolled: '2026-03-02' },
    capabilities: ['display', 'large-display', 'audio', 'video', 'keyboard', 'compute', 'gpu', 'storage', 'windows-runtime'],
    network: { transport: 'ethernet', address: '10.0.7.10', latencyMs: 2, signal: 1 },
    lastSeen: now - 1000 * 60 * 42,
    state: { cpu: 0.04, memory: 0.12, storageUsed: 3.4, storageTotal: 8 },
  },
  {
    id: 'relic-tv',
    name: 'Relic TV',
    type: 'tv',
    status: 'online',
    presence: 'connected',
    location: 'Living Room',
    hardware: '85" · 4K HDR · RELIC CORE',
    identity: { fingerprint: 'RLC·A10D·5C33·19BE', trust: 'verified', enrolled: '2026-04-11' },
    capabilities: ['display', 'large-display', 'audio', 'video', 'remote-input', 'microphone'],
    network: { transport: 'ethernet', address: '10.0.7.30', latencyMs: 3, signal: 1 },
    lastSeen: now,
    state: { power: true, volume: 34, input: 'RELIC' },
  },
  {
    id: 'relic-phone',
    name: 'Relic Phone',
    type: 'phone',
    status: 'online',
    presence: 'nearby',
    location: 'Nearby',
    hardware: 'ARM64 · 6.3" OLED',
    identity: { fingerprint: 'RLC·4E90·D2A7·6B08', trust: 'verified', enrolled: '2026-02-19' },
    capabilities: ['display', 'touch', 'camera', 'gps', 'microphone', 'cellular', 'audio', 'video'],
    network: { transport: 'wifi', address: '10.0.7.44', latencyMs: 6, signal: 0.81 },
    lastSeen: now,
    battery: 0.72,
    state: { ringer: true },
  },
  {
    id: 'relic-car',
    name: 'Relic Car',
    type: 'car',
    status: 'online',
    presence: 'connected',
    location: 'Garage',
    hardware: 'RELIC DRIVE · 15" DISPLAY',
    identity: { fingerprint: 'RLC·C7F1·3390·8DD4', trust: 'verified', enrolled: '2026-05-30' },
    capabilities: ['display', 'gps', 'audio', 'climate', 'navigation', 'microphone', 'locks'],
    network: { transport: 'lte', address: 'mesh://relic-car', latencyMs: 38, signal: 0.66 },
    lastSeen: now,
    battery: 0.78,
    state: { cabin: 72, locked: true, range: 286, charging: false, seatHeat: 0, defrost: false, fan: 2 },
  },
  {
    id: 'relic-home',
    name: 'Relic Home',
    type: 'home',
    status: 'online',
    presence: 'connected',
    location: 'Residence',
    hardware: 'HOME HUB · THREAD / MATTER',
    identity: { fingerprint: 'RLC·90AE·7713·F25C', trust: 'verified', enrolled: '2026-01-08' },
    capabilities: ['lighting', 'locks', 'security', 'audio', 'microphone'],
    network: { transport: 'thread', address: 'thread://relic-home', latencyMs: 9, signal: 0.9 },
    lastSeen: now,
    state: { lights: 0.4, scene: 'EVENING', frontDoor: 'LOCKED', security: 'ARMED · STAY' },
  },
  {
    id: 'relic-thermostat',
    name: 'Relic Thermostat',
    type: 'thermostat',
    status: 'online',
    presence: 'connected',
    location: 'Hallway',
    hardware: 'RELIC THERMOSTAT · ROUND DISPLAY',
    identity: { fingerprint: 'RLC·18D5·C0A9·44E7', trust: 'verified', enrolled: '2026-01-08' },
    capabilities: ['display', 'temperature', 'fan', 'climate'],
    network: { transport: 'thread', address: 'thread://relic-thermostat', latencyMs: 11, signal: 0.88 },
    lastSeen: now,
    state: {},
  },
]

export const capabilityLabels: Record<string, string> = {
  display: 'DISPLAY',
  'large-display': 'LARGE DISPLAY',
  audio: 'AUDIO',
  video: 'VIDEO',
  'remote-input': 'REMOTE INPUT',
  keyboard: 'KEYBOARD',
  touch: 'TOUCH',
  camera: 'CAMERA',
  gps: 'GPS',
  microphone: 'MICROPHONE',
  cellular: 'CELLULAR',
  climate: 'CLIMATE',
  navigation: 'NAVIGATION',
  temperature: 'TEMPERATURE',
  fan: 'FAN',
  compute: 'COMPUTE',
  gpu: 'GPU',
  storage: 'STORAGE',
  'windows-runtime': 'WINDOWS RUNTIME',
  lighting: 'LIGHTING',
  locks: 'LOCKS',
  security: 'SECURITY',
}
