import {
  Box,
  Car,
  Cloud,
  Code,
  Compass,
  Cuboid,
  File,
  Folder,
  Gamepad2,
  Globe,
  Hammer,
  Image,
  Laptop,
  LayoutGrid,
  Link,
  Monitor,
  MonitorSmartphone,
  MousePointer2,
  Music,
  Play,
  Settings,
  Shield,
  Smartphone,
  Sparkle,
  Table,
  Thermometer,
  Tv,
  House,
  Zap,
  Aperture,
  type LucideIcon,
} from 'lucide-react'

/** Restrained icon system: lucide, hairline stroke, keyed by name. */
const map: Record<string, LucideIcon> = {
  sparkle: Sparkle,
  folder: Folder,
  globe: Globe,
  settings: Settings,
  devices: MonitorSmartphone,
  grid: LayoutGrid,
  file: File,
  play: Play,
  image: Image,
  compass: Compass,
  table: Table,
  box: Box,
  chrome: Aperture,
  cube: Cuboid,
  code: Code,
  music: Music,
  gamepad: Gamepad2,
  hammer: Hammer,
  tv: Tv,
  phone: Smartphone,
  car: Car,
  thermostat: Thermometer,
  thermometer: Thermometer,
  home: House,
  laptop: Laptop,
  desktop: Monitor,
  cloud: Cloud,
  shield: Shield,
  link: Link,
  zap: Zap,
  mouse: MousePointer2,
}

export function Icon({ name, size = 16, className, strokeWidth = 1.25 }: { name?: string; size?: number; className?: string; strokeWidth?: number }) {
  const C = (name && map[name]) || Box
  return <C size={size} strokeWidth={strokeWidth} className={className} />
}

export const deviceIcon: Record<string, string> = {
  laptop: 'laptop',
  desktop: 'desktop',
  tv: 'tv',
  phone: 'phone',
  car: 'car',
  thermostat: 'thermostat',
  home: 'home',
}
